RondinesWeb/Models/ErrorViewModel.cs
namespace RondinesWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RondinesWeb/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RondinesWeb.Models;
using System.Diagnostics;

namespace RondinesWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RondinesWeb/Controllers/IncidentesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class IncidentesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Controllers/RondasController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class RondasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Controllers/RondinesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class RondinesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VistaVacia()
        {
            return View("Views/Rondines/VistaVacia.cshtml");
        }
    }
}

RondinesWeb/Controllers/StatusIncidentesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class StatusIncidentesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Controllers/TypesIncidentesController.cs
using Microsoft.AspNetCore.Mvc;

namespace RondinesWeb.Controllers
{
    public class TypesIncidentesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RondinesWeb/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles{
    <!-- DataTables -->
    <link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- Responsive datatable examples -->
    <link href="~/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Lorem Ipsum</h4>

                <table id="datatable" class="table table-bordered dt-responsive  nowrap w-100">
                    <thead>
                        <tr>
                            <th>Data 1</th>
                            <th>Data 2</th>
                            <th>Data 3</th>
                            <th>Data 4</th>
                            <th>Acción</th>
                        </tr>
                    </thead>


                    <tbody>
                        <tr>
                            <td>2011/04/25</td>
                            <td>Tiger Nixon</td>
                            <td>61</td>
                            <td><button type="button" class="btn btn-warning btn-rounded btn-sm w-sm waves-effect waves-light">Pendiente</button></td>
                            <td>
                                <button type="button" class="btn btn-link btn-rounded waves-effect">
                                    <i class="bx bx-show font-size-16 align-middle me-2"></i>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>2011/07/25</td>
                            <td>Garrett Winters</td>
                            <td>63</td>
                            <td><button type="button" class="btn btn-success btn-rounded btn-sm w-sm waves-effect waves-light">Pagado</button></td>
                            <td>
                                <button type="button" class="btn btn-link btn-rounded waves-effect">
                                    <i class="bx bx-show font-size-16 align-middle me-2"></i>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>2009/01/12</td>
                            <td>Ashton Cox</td>
                            <td>66</td>
                            <td><button type="button" class="btn btn-warning btn-rounded btn-sm w-sm waves-effect waves-light">Pendiente</button></td>
                            <td>
                                <button type="button" class="btn btn-link btn-rounded waves-effect">
                                    <i class="bx bx-show font-size-16 align-middle me-2"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->


<div class="row">
    <div class="col-xl-8">
        <div class="card">
            <div class="card-body">
                <div class="clearfix">
                    <div class="float-end">
                        <div class="input-group input-group-sm">
                            <select class="form-select form-select-sm">
                                <option value="JA" selected>Jan</option>
                                <option value="DE">Dec</option>
                                <option value="NO">Nov</option>
                                <option value="OC">Oct</option>
                            </select>
                            <label class="input-group-text">Month</label>
                        </div>
                    </div>
                    <h4 class="card-title mb-4">Earning</h4>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <div class="text-muted">
                            <div class="mb-4">
                                <p>This month</p>
                                <h4>$2453.35</h4>
                                <div><span class="badge badge-soft-success font-size-12 me-1"> + 0.2% </span> From previous period</div>
                            </div>

                            <div>
                                <a href="javascript: void(0);" class="btn btn-primary waves-effect waves-light btn-sm">View Details <i class="mdi mdi-chevron-right ms-1"></i></a>
                            </div>

                            <div class="mt-4">
                                <p class="mb-2">Last month</p>
                                <h5>$2281.04</h5>
                            </div>

                        </div>
                    </div>

                    <div class="col-lg-8">
                        <div id="line-chart" class="apex-charts" dir="ltr"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title mb-4">Sales Analytics</h4>

                <div>
                    <div id="donut-chart" class="apex-charts"></div>
                </div>

                <div class="text-center text-muted">
                    <div class="row">
                        <div class="col-4">
                            <div class="mt-4">
                                <p class="mb-2 text-truncate"><i class="mdi mdi-circle text-primary me-1"></i> Product A</p>
                                <h5>$ 2,132</h5>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="mt-4">
                                <p class="mb-2 text-truncate"><i class="mdi mdi-circle text-success me-1"></i> Product B</p>
                                <h5>$ 1,763</h5>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="mt-4">
                                <p class="mb-2 text-truncate"><i class="mdi mdi-circle text-danger me-1"></i> Product C</p>
                                <h5>$ 973</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->

<!-- JAVASCRIPT -->
<script src="~/assets/libs/jquery/jquery.min.js"></script>
<script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/libs/metismenu/metisMenu.min.js"></script>
<script src="~/assets/libs/simplebar/simplebar.min.js"></script>
<script src="~/assets/libs/node-waves/waves.min.js"></script>

<!-- Required datatable js -->
<script src="~/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="~/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<!-- Buttons examples -->
<script src="~/assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>


<!-- apexcharts -->
<script src="~/assets/libs/apexcharts/apexcharts.min.js"></script>

<!-- Saas dashboard init -->
<script src="~/assets/js/pages/saas-dashboard.init.js"></script>

<!-- Datatable init js -->
<script src="~/assets/js/pages/datatables.init.js"></script>

<script src="~/assets/js/app.js"></script>

RondinesWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RondinesWeb/Views/Rondines/FormAddPoint.cshtml
<!-- sample modal content -->
<div id="addPoint" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Agregar punto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="mt-3">
                    <label class="mb-1">Descripción</label>
                    <textarea id="textarea" class="form-control" maxlength="225" rows="4"
                                placeholder="">
                    </textarea>
                </div>

                 <div class="mt-3">
                    <label class="form-label">Coordenadas</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input class="form-control" type="text" placeholder="Lat">
                        </div>
                        
                        <div class="col-md-6">
                            <input class="form-control" type="text" placeholder="Long">
                        </div>
                    </div>
                </div>

                 <div class="mt-3">
                    <label for="formFile" class="form-label">Mapa ( URL / Foto )</label>
                    <input class="form-control" type="file" id="formFile">
                </div>

                                   
            <div class="modal-footer">
                
                <button 
                type="button" 
                class="btn btn-primary waves-effect waves-light"
                >Aceptar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

RondinesWeb/Views/Rondines/FormAddRondin.cshtml
<!-- sample modal content -->
<div id="addRondin" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Agregar rondin</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div>
                            <label class="form-label">Nombre</label>
                            <input class="form-control" type="text" placeholder="">
                        </div>
                    </div>
                </div>

                <div class="mt-3">
                    <label class="mb-1">Descripción</label>
                    <textarea id="textarea" class="form-control" maxlength="225" rows="4"
                                placeholder="">
                    </textarea>
                </div>

                    <div class="col-lg-6 mt-3">
                    <div>
                        <label class="form-label">Alcance</label>
                        <input class="form-control" type="text" placeholder="mts">
                    </div>
                </div>
                                   
            <div class="modal-footer">
                <a href=@Url.Action("VistaVacia", "Rondines")
                class="btn btn-primary waves-effect waves-light">
                </a>
                <input 
                type="submit" 
                class="btn btn-primary waves-effect waves-light"
                value="Aceptar"
                name="Aceptar"
                onclick="location.href='<%: Url.Action('EditRondin', 'Rondines') %>'"
                />
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

RondinesWeb/Views/Rondines/FormEditRondin.cshtml
<!-- sample modal content -->
<div id="editRondin" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Editar rondin</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div>
                            <label class="form-label">Nombre</label>
                            <input class="form-control" type="text" placeholder="">
                        </div>
                    </div>
                </div>

                <div class="mt-3">
                    <label class="mb-1">Descripción</label>
                    <textarea id="textarea" class="form-control" maxlength="225" rows="4"
                                placeholder="">
                    </textarea>
                </div>

                    <div class="col-lg-6 mt-3">
                    <div>
                        <label class="form-label">Alcance</label>
                        <input class="form-control" type="text" placeholder="mts">
                    </div>
                </div>

                <div class="modal-footer">
                    <a href=@Url.Action("VistaVacia", "Rondines")
                    class="btn btn-primary waves-effect waves-light">
                    </a>
                    <button type="button" class="btn btn-primary waves-effect waves-light">Guardar</button>
                </div>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>

RondinesWeb/Views/Shared/_sidebar.cshtml
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-menu">Menu</li>
                <li>
                    <a href=@Url.Action("Index", "Dashboard") class="waves-effect">
                        <i class="bx bx-grid-alt"></i>
                        <span key="t-dashboards">Dashboards</span>
                    </a>
                </li>
                <li>
                    <a href=@Url.Action("Index", "Rondines") class="waves-effect">
                        <i class="bx bx-shield"></i>
                        <span key="t-rondines">Rondines</span>
                    </a>
                </li>
@*                <li>
                    <a href=@Url.Action("VistaVacia", "Rondines") class="waves-effect">
                        <i class="bx bx-shield"></i>
                        <span key="t-rondines">Editar Rondin</span>
                    </a>
                </li>*@
                <li>
                    <a href=@Url.Action("Index", "Rondas") class="waves-effect">
                        <i class="bx bx-walk"></i>
                        <span key="t-rondas">Rondas</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="bx bx-error-circle"></i>
                        <span key="t-incidentes">Incidentes</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href=@Url.Action("Index", "Incidentes") class="waves-effect">Incidentes</a></li>
                        <li><a href=@Url.Action("Index", "TypesIncidentes") class="waves-effect">Tipos de incidentes</a></li>
                        <li><a href=@Url.Action("Index", "StatusIncidentes") class="waves-effect">Estatus de incidentes</a></li>
                    </ul>
                </li>

            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

RondinesWeb/Views/Shared/_topbar.cshtml
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
@*                <a href=@Url.Action("Index", "Dashboard") class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="~/assets/images/logo.svg" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="~/assets/images/logo-dark.png" alt="" height="17">
                    </span>
                </a>*@

                <a href=@Url.Action("Index", "Dashboard") class="logo logo-light">
                    <span class="logo-sm">
                        <img src="~/assets/images/logo-cuadrado-amm.png" alt="" height="28">
                    </span>
                    <span class="logo-lg">
                        <img src="~/assets/images/logo-cuadrado-amm.png" alt="" height="50">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

@*            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="bx bx-search-alt"></span>
                </div>
            </form>*@
        </div>

        <div class="d-flex">

     @*       <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                     aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>*@

            @*<div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img id="header-lang-img" src="~/assets/images/flags/us.jpg" alt="Header Language" height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-end">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="en">
                        <img src="assets/images/flags/us.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">English</span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="sp">
                        <img src="assets/images/flags/spain.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="gr">
                        <img src="assets/images/flags/germany.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="it">
                        <img src="assets/images/flags/italy.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="ru">
                        <img src="assets/images/flags/russia.jpg" alt="user-image" class="me-1" height="12"> <span class="align-middle">Russian</span>
                    </a>
                </div>
            </div>*@

            @*<div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge bg-danger rounded-pill">3</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#!" class="small" key="t-view-all"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-primary rounded-circle font-size-16">
                                        <i class="bx bx-cart"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-your-order">Your order is placed</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-min-ago">3 min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="~/assets/images/users/avatar-3.jpg"
                                     class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mt-0 mb-1">James Lemire</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-simplified">It will seem like simplified English.</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-hours-ago">1 hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-success rounded-circle font-size-16">
                                        <i class="bx bx-badge-check"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-shipped">Your item is shipped</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-min-ago">3 min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>

                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="assets/images/users/avatar-4.jpg"
                                     class="me-3 rounded-circle avatar-xs" alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Salena Layfield</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-occidental">As a skeptical Cambridge friend of mine occidental.</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-hours-ago">1 hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 text-center" href="javascript:void(0)">
                            <i class="mdi mdi-arrow-right-circle me-1"></i> <span key="t-view-more">View More..</span>
                        </a>
                    </div>
                </div>
            </div>*@

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="~/assets/images/users/avatar-2.jpg"
                         alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ms-1" key="t-admin">Admin</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    @*<a class="dropdown-item" href="#"><i class="bx bx-user font-size-16 align-middle me-1"></i> <span key="t-profile">Profile</span></a>
                    <a class="dropdown-item" href="#"><i class="bx bx-wallet font-size-16 align-middle me-1"></i> <span key="t-my-wallet">My Wallet</span></a>
                    <a class="dropdown-item d-block" href="#"><span class="badge bg-success float-end">11</span><i class="bx bx-wrench font-size-16 align-middle me-1"></i> <span key="t-settings">Settings</span></a>
                    <a class="dropdown-item" href="#"><i class="bx bx-lock-open font-size-16 align-middle me-1"></i> <span key="t-lock-screen">Lock screen</span></a>*@
                    @*<div class="dropdown-divider"></div>*@
                    <a class="dropdown-item text-danger" href=@Url.Action("Index", "Auth")><i class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span key="t-logout">Cerrar sesión</span></a>
                </div>
            </div>

 @*           <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="bx bx-cog bx-spin"></i>
                </button>
            </div>*@


        </div>
    </div>
</header>